# -*- coding: utf-8 -*-
"""Clothes Fashion MNIST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SSNeXJ2-iGrUfx1H5spxTi9t9dBzMm3U
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

from tensorflow.keras.datasets import fashion_mnist

(X_train,y_train),(X_test,y_test)=tf.keras.datasets.fashion_mnist.load_data()

# Normalizing the image
X_train=X_train.astype("float32")/255.0
X_test=X_test.astype("float32")/255.0

from tensorflow.keras import layers,models,Sequential

fcnn_model=models.Sequential([
    layers.Flatten(input_shape=(28,28)),

    layers.Dense(300,activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.5),

    layers.Dense(100,activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.4),

    layers.Dense(10,activation='softmax')

   ])

# Compiling the fcnn
fcnn_model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

# Training with early stopping
early_stopping=tf.keras.callbacks.EarlyStopping(patience=3,restore_best_weights=True)

fcnn_model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    callbacks=[early_stopping])

loss, accuracy = fcnn_model.evaluate(X_test, y_test)

print(f"Test Accuracy: {accuracy:.4f}")



# CNN expects 4D input: (samples, height, width, channels)
X_train_cnn = X_train.reshape(-1, 28, 28, 1)
X_test_cnn = X_test.reshape(-1, 28, 28, 1)

cnn_model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    layers.MaxPooling2D((2,2)),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(10, activation='softmax')
])

cnn_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

cnn_history = cnn_model.fit(
    X_train_cnn, y_train,
    epochs=10,
    batch_size=32,
    validation_split=0.2
)

cnn_test_loss, cnn_test_acc = cnn_model.evaluate(X_test_cnn, y_test)
print("CNN Test Accuracy:", cnn_test_acc)

cnn_model.save("cnn_model.h5")

class_names = [
    "T-shirt / Top",
    "Trouser",
    "Pullover",
    "Dress",
    "Coat",
    "Sandal",
    "Shirt",
    "Sneaker",
    "Bag",
    "Ankle Boot"
]

import gradio as gr
import numpy as np
import cv2
import tensorflow as tf
from tensorflow.keras.models import load_model

# Load trained CNN model
model = load_model("cnn_model.h5")

# Class labels
class_names = [
    "T-shirt / Top", "Trouser", "Pullover", "Dress", "Coat",
    "Sandal", "Shirt", "Sneaker", "Bag", "Ankle Boot"
]

def predict_fashion(image):
    # Convert to grayscale
    image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Resize to 28x28
    image = cv2.resize(image, (28, 28))

    # Normalize
    image = image.astype("float32") / 255.0

    # Reshape for CNN
    image = image.reshape(1, 28, 28, 1)

    # Predict
    predictions = model.predict(image)
    confidence = float(np.max(predictions))
    predicted_class = class_names[np.argmax(predictions)]

    return predicted_class, confidence

# Gradio UI
interface = gr.Interface(
    fn=predict_fashion,
    inputs=gr.Image(type="numpy", label="Upload Clothing Image"),
    outputs=[
        gr.Textbox(label="Predicted Class"),
        gr.Number(label="Confidence")
    ],
    title="👕 Fashion MNIST Clothing Classifier",
    description="CNN-based Fashion MNIST classifier deployed on Hugging Face Spaces",
)

interface.launch()

interface = gr.Interface(
    fn=predict_fashion,
    inputs=gr.Image(type="numpy", label="Upload Clothing Image"),
    outputs=[
        gr.Textbox(label="Predicted Class"),
        gr.Number(label="Confidence Score")
    ],
    title="👕 Fashion MNIST Clothing Classifier",
    description="Upload an image of a clothing item. The CNN model will predict the category.",
    theme="default"
)

interface.launch()

cnn_model.save("cnn_model.h5")







